config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  root 'topics#index'
  devise_for :users
  resources :users, only: :show

  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks, only: [] do
    resources :likes, only: [:index, :create, :destroy]
  end
  post 'incoming' => 'incoming#incoming'
  get 'about' => 'welcome#about'
  get 'welcome' => 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected
  rescue_from Pundit::NotAuthorizedError do
    flash[:alert] = "you're not allowed to do that"
    redirect_to :back
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.build(bookmark_params)
    @bookmark.user = current_user
    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was saved successfully."
      redirect_to [@topic, @bookmark]
    else
      flash[:alert] = "There was an error saving the bookmark. Please try again."
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)
    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was updated successfully."
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash[:alert] = "There was an error updating the bookmark. Please try again."
      render :edit
    end
  end

  def destroy
     @bookmark = Bookmark.find(params[:id])
     authorize @bookmark

     if @bookmark.destroy
       flash[:notice] = "\"#{@bookmark.url}\" was deleted successfully."
       redirect_to @bookmark.topic
     else
       flash.now[:alert] = "There was an error deleting the bookmark."
       render :show
     end
   end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_filter :authenticate_user!
  skip_before_action :verify_authenticity_token
  
  def incoming
    email = params[:from]
    user = User.find_by(email: email)
    url = params['stripped-text']
    # topic = Topic.find_by(title: topic)
    topic = Topic.create(title: params[:subject])
    bookmark = Bookmark.create(user: user, url: url, topic: topic)
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)
    authorize @like

    if @like.save
      flash[:notice] = "Link liked."
    else
      flash[:alert] = "Liked failed."
    end

    redirect_to :back
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.find(params[:id])
    authorize @like

    if @like.destroy
      flash[:notice] = "Link unliked."
    else
      flash[:alert] = "Unliked failed."
    end

    redirect_to :back
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(user)
      user_path(current_user)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic was updated successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash.now[:alert] = "There was an error deleting the topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    likes = Like.where(user_id: @user.id)
    @user_liked_bookmarks = Bookmark.where(user_id: @user.id, id: likes.pluck(:bookmark_id))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.erb
<% bookmarks.each do |bookmark| %>
  <div class="row">
    <div class="col-md-2">
       <%= link_to bookmark.url, [bookmark.topic, bookmark] %>
    </div>
    <div>
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
    </div>
  </div>
<% end %>

app/views/bookmarks/_form.html.erb
<%= form_for [topic, bookmark] do |f| %>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>
<div class="row">
  <div = class="col-md-8">
    <%= render partial: 'form', locals: {topic: @bookmark.topic, bookmark: @bookmark } %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<div class="row">
  <div = class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic, bookmark: @bookmark } %>
  </div>
</div>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.url %></h1>
<div class="col-md-4">
  <% if policy(@bookmark).update? %>
    <%= link_to "Edit Bookmark", edit_topic_bookmark_path, class: 'btn btn-success' %>
    <%= link_to "Delete Bookmark", [@bookmark.topic, @bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this bookmark?' } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Topics", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= link_to current_user.email, user_path(current_user) %></strong> <br/>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% end %>

        <% if not user_signed_in? %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-dismissible alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<% @topics.each do |topic| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to topic.title, topic %>
      </h4>
      <small>
        <%= render partial: 'bookmarks/bookmark', locals: { bookmarks: topic.bookmarks } %>
      </small>
    </div>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<div class="row">
  <div = class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="page-header">
  <h1>Topics</h1> <br>
  <%= link_to "New Topic", new_topic_path, class: 'btn btn-xs btn-success' %>
</div>
<div class="row">
</div>
<div class="row">
 <div class="col-md-8">
   <%= render partial: 'topics/topic', locals: { topic: @topic } %>
 </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<div class="row">
  <div = class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
<%= link_to "New bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
<% @topic.bookmarks.each do |bookmark| %>
  <div class="media">
   <div class="media-body">
     <h4 class="media-heading">
       <%= link_to bookmark.url, topic_bookmark_path(@topic, bookmark) %>
     </h4>
   </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <h2 class="media-heading"><%= @user.email %></h2>
        <% @user_liked_bookmarks.each do |bookmark| %>
          <li><%= bookmark.url %></li>
          <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Bookmarks</h1>
<p>Created by: Eon</p>

app/views/welcome/index.html.erb
<h1>All Bookmarks</h1>